### ISSUE TITLE
Docker導入する

### ISSUE THREAD

**Issue by azurata09** [t4t5u0/ManabaCrawlerServer#4]
Dockerで環境を汚さないようにする

**Comment by azurata09** [comment]
なんかコンテナ内から接続すると普通に出来るのにコンテナ外から接続すると`ERR_EMPTY_RESPONSE`が出る

**Comment by t4t5u0** [comment]
ブランチ切って、developかfeatureにpushしてほしい

**Comment by t4t5u0** [comment]
あ、これはコントリビューターに追加しないと無理でした。どうしようかな

**Comment by t4t5u0** [comment]
```
docker run -it -p localhost:8000:8000
```
みたいな感じで起動するとport forwarding できた気がする

**Comment by azurata09** [comment]
一旦compose抜きでやってみます

**Comment by t4t5u0** [comment]
composeで書いてたのね。そしたらちょっとまって

**Comment by azurata09** [comment]
一旦ドラフトプルリク出してみます

**Comment by t4t5u0** [comment]
ok
